# Generated by Django 2.2.5 on 2019-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190922_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielinks',
            options={'verbose_name_plural': 'Movie links'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('en', 'ENGLISH'), ('gr', 'GERMAN')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('ra', 'RECENTLY ADDED'), ('mw', 'MOST WATCHED'), ('tr', 'TOP RATED')], max_length=2),
        ),
    ]
